//------------------------------------------------------------------------------
// <auto-generated>
//     Date time = 10/16/2012 4:32:31 PM
//     This code was generated by tool,Version=12.10.11.
//     Changes to this code may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using GetTogether.Data;
using GetTogether.Mapping;

namespace GetTogether.Studio.Database.DAL
{
    public partial class DO_ColumnDescription : DOBase<DO_ColumnDescription.UO_ColumnDescription, DO_ColumnDescription.UOList_ColumnDescription>
    {
        public static ConnectionInformation GetConnectionInformation()
        {
            return null;
        }
        public override ConnectionInformation GetDefaultConnectionInformation()
        {
            return GetConnectionInformation();
        }
        public enum Columns
        {
            /// <summary>
            ///Primary Key,Database Type:System.String
            /// </summary>
            Name,
            /// <summary>
            ///Database Type:System.Object
            /// </summary>
            Remark,
        }
        public DO_ColumnDescription()
        {
        }
        public partial class UO_ColumnDescription : UOBase<UO_ColumnDescription, UOList_ColumnDescription>
        {
            public override ConnectionInformation GetDefaultConnectionInformation()
            {
                return GetConnectionInformation();
            }
            #region Columns
            private string _Name;
            /// <summary>
            ///Primary Key,Database Type:System.String
            /// </summary>
            [Mapping("Name")]
            public string Name
            {
                get
                {
                    return _Name;
                }
                set
                {
                    _Name = value;
                }
            }
            private string _Remark;
            /// <summary>
            ///Database Type:System.Object
            /// </summary>
            [Mapping("Remark")]
            public string Remark
            {
                get
                {
                    return _Remark;
                }
                set
                {
                    _Remark = value;
                }
            }
            #endregion

            public UO_ColumnDescription()
            {
            }
        }
        public partial class UOList_ColumnDescription : GetTogether.ObjectBase.ListBase<UO_ColumnDescription>
        {
            public UOList_ColumnDescription()
            {
            }
        }
    }
}
