//------------------------------------------------------------------------------
// <auto-generated>
//     Date time = 10/11/2012 5:29:57 PM
//     This code was generated by tool,Version=2.0.1004.01.
//     Changes to this code may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using GetTogether.Data;
using GetTogether.Mapping;

namespace GetTogether.Studio.Database.DAL
{
    public partial class DO_Common : DOBase<DO_Common.UO_Test, DO_Common.UOList_Common>
    {
        public static ConnectionInformation GetConnectionInformation()
        {
            return new ConnectionInformation(
                    "Table Name",
                    "Connection Key",
                    new string[] { "Primary Key(s)" }, DatabaseType.SQLServer
                );
        }
        public override ConnectionInformation GetDefaultConnectionInformation()
        {
            return GetConnectionInformation();
        }
        public enum Columns
        {

        }
        public DO_Common()
        {
        }
        public partial class UO_Test : UOBase<UO_Test, UOList_Common>
        {
            public override ConnectionInformation GetDefaultConnectionInformation()
            {
                return GetConnectionInformation();
            }
            
            public UO_Test()
            {
            }
        }
        public partial class UOList_Common : GetTogether.ObjectBase.ListBase<UO_Test>
        {
            public UOList_Common()
            {
            }
        }
    }
}
