//------------------------------------------------------------------------------
// <auto-generated>
//     Date time = 12/17/2012 11:47:01 AM
//     This code was generated by tool,Version=12.10.11.
//     Changes to this code may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using GetTogether.Data;
using GetTogether.Mapping;

namespace GetTogether.Studio.Database.DAL
{
    public partial class DO_ColumnDetail : DOBase<DO_ColumnDetail.UO_ColumnDetail, DO_ColumnDetail.UOList_ColumnDetail>
    {
        public static ConnectionInformation GetConnectionInformation()
        {
            return new ConnectionInformation(
                    "ColumnDetail",
                    "Connection Key",
                    new string[] { "column_name" }, DatabaseType.SQLServer
                );
        }
        public override ConnectionInformation GetDefaultConnectionInformation()
        {
            return GetConnectionInformation();
        }
        public enum Columns
        {
            /// <summary>
            ///Primary Key
            /// </summary>
            ColumnName,
            DefaultValue,
            IsNullable,
            DataType,
            MaxLength,
        }
        public DO_ColumnDetail()
        {
        }
        public partial class UO_ColumnDetail : UOBase<UO_ColumnDetail, UOList_ColumnDetail>
        {
            public override ConnectionInformation GetDefaultConnectionInformation()
            {
                return GetConnectionInformation();
            }
            #region Columns
            private System.String _ColumnName;
            /// <summary>
            ///Primary Key
            /// </summary>
            [Mapping("ColumnName,un-update")]
            public System.String ColumnName
            {
                get
                {
                    return _ColumnName;
                }
                set
                {
                    _ColumnName = value;
                }
            }
            private System.String _DefaultValue;
            [Mapping("DefaultValue")]
            public System.String DefaultValue
            {
                get
                {
                    return _DefaultValue;
                }
                set
                {
                    _DefaultValue = value;
                }
            }
            private System.Int32 _IsNullable;
            [Mapping("IsNullable")]
            public System.Int32 IsNullable
            {
                get
                {
                    return _IsNullable;
                }
                set
                {
                    _IsNullable = value;
                }
            }
            private System.String _DataType;
            [Mapping("DataType")]
            public System.String DataType
            {
                get
                {
                    return _DataType;
                }
                set
                {
                    _DataType = value;
                }
            }
            private System.Int32 _MaxLength;
            [Mapping("MaxLength")]
            public System.Int32 MaxLength
            {
                get
                {
                    return _MaxLength;
                }
                set
                {
                    _MaxLength = value;
                }
            }
            #endregion
            public UO_ColumnDetail()
            {
            }
        }
        public partial class UOList_ColumnDetail : GetTogether.ObjectBase.ListBase<UO_ColumnDetail>
        {
            public UOList_ColumnDetail()
            {
            }
        }
    }
}
