//------------------------------------------------------------------------------
// <auto-generated>
//     Date time = 10/14/2012 7:11:50 PM
//     This code was generated by tool,Version=12.10.11.
//     Changes to this code may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using GetTogether.Data;
using GetTogether.Mapping;

namespace GetTogether.Studio.Database.DAL
{
    public partial class DO_StoreProcedureParameter : DOBase<DO_StoreProcedureParameter.UO_StoreProcedureParameter, DO_StoreProcedureParameter.UOList_StoreProcedureParameter>
    {
        public static ConnectionInformation GetConnectionInformation()
        {
            return new ConnectionInformation(
                "Table Name",
                "Connection Key",
                new string[] { "Primary Key(s)" }, DatabaseType.SQLServer
            );
        }
        public override ConnectionInformation GetDefaultConnectionInformation()
        {
            return GetConnectionInformation();
        }
        public enum Columns
        {
            Name,
            DataType,
            Length,
            IsNullAble,
            IsOutParam,
        }
        public DO_StoreProcedureParameter()
        {
        }
        public partial class UO_StoreProcedureParameter : UOBase<UO_StoreProcedureParameter, UOList_StoreProcedureParameter>
        {
            public override ConnectionInformation GetDefaultConnectionInformation()
            {
                return GetConnectionInformation();
            }
            #region Columns
            private System.String _Name;
            [Mapping("Name")]
            public System.String Name
            {
                get
                {
                    return _Name;
                }
                set
                {
                    _Name = value;
                }
            }
            private System.String _DataType;
            [Mapping("DataType")]
            public System.String DataType
            {
                get
                {
                    return _DataType;
                }
                set
                {
                    _DataType = value;
                }
            }
            private System.Int16 _Length;
            [Mapping("Length")]
            public System.Int16 Length
            {
                get
                {
                    return _Length;
                }
                set
                {
                    _Length = value;
                }
            }
            private System.Int32 _IsNullAble;
            [Mapping("IsNullAble")]
            public System.Int32 IsNullAble
            {
                get
                {
                    return _IsNullAble;
                }
                set
                {
                    _IsNullAble = value;
                }
            }
            private System.Int32 _IsOutParam;
            [Mapping("IsOutParam")]
            public System.Int32 IsOutParam
            {
                get
                {
                    return _IsOutParam;
                }
                set
                {
                    _IsOutParam = value;
                }
            }
            #endregion

            public UO_StoreProcedureParameter()
            {
            }
        }
        public partial class UOList_StoreProcedureParameter : GetTogether.ObjectBase.ListBase<UO_StoreProcedureParameter>
        {
            public UOList_StoreProcedureParameter()
            {
            }
        }
    }
}
